# build.yaml
# This file tells the Home Assistant builder to use a specific base image
# for building the addon. We use the official Nginx base image, which
# comes with Nginx pre-installed, avoiding network-dependent installations.
build_from:
  aarch64: "ghcr.io/home-assistant/aarch64-base-nginx:15.1.0"
  amd64: "ghcr.io/home-assistant/amd64-base-nginx:15.1.0"
  armhf: "ghcr.io/home-assistant/armhf-base-nginx:15.1.0"
  armv7: "ghcr.io/home-assistant/armv7-base-nginx:15.1.0"
  i386: "ghcr.io/home-assistant/i386-base-nginx:15.1.0"