name: "Hello World"
version: "1.0.1"
slug: "hello_world"
description: "A simple Hello World addon for Home Assistant."
arch:
  - "aarch64"
  - "amd64"
  - "armhf"
  - "armv7"
  - "i386"
init: false
ingress: true
ingress_port: 8099
panel_icon: "mdi:earth"
panel_title: "Hello World"